version: 2.0
jobs:
  build-node-11: &default
    docker:
      - image: circleci/node:11
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 
          name: Git Submodule Update
          command: git submodule update --init --recursive
      - run:
          name: Lint
          command: npm run lint-check
      - run:
          name: Test
          command: npm test
  build-node-10:
    <<: *default
    docker:
      - image: circleci/node:10
  # build-node-9:
  #   <<: *default
  #   docker:
  #     - image: circleci/node:9
  # build-node-8:
  #   <<: *default
  #   docker:
  #     - image: circleci/node:8
  # build-node-7:
  #   <<: *default
  #   docker:
  #     - image: circleci/node:7


workflows:
  version: 2
  test-all-versions:
    jobs:
      # - build-node-7
      # - build-node-8
      # - build-node-9
      - build-node-10
      - build-node-11
